// <auto-generated />
using System;
using DataTierWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTierWebServer.Migrations
{
    [DbContext(typeof(DBManager))]
    partial class DBManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Property<uint>("AcctNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcctNo");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AcctNo = 7791u,
                            AccountName = "Savings Account",
                            Balance = 59353,
                            UserId = 1
                        },
                        new
                        {
                            AcctNo = 5441u,
                            AccountName = "Savings Account",
                            Balance = 13292,
                            UserId = 2
                        },
                        new
                        {
                            AcctNo = 6390u,
                            AccountName = "Savings Account",
                            Balance = 20644,
                            UserId = 3
                        },
                        new
                        {
                            AcctNo = 8839u,
                            AccountName = "Savings Account",
                            Balance = 29277,
                            UserId = 4
                        },
                        new
                        {
                            AcctNo = 3937u,
                            AccountName = "Savings Account",
                            Balance = 89484,
                            UserId = 5
                        },
                        new
                        {
                            AcctNo = 7524u,
                            AccountName = "Savings Account",
                            Balance = 49734,
                            UserId = 6
                        },
                        new
                        {
                            AcctNo = 5181u,
                            AccountName = "Savings Account",
                            Balance = 92034,
                            UserId = 7
                        },
                        new
                        {
                            AcctNo = 5291u,
                            AccountName = "Savings Account",
                            Balance = 23418,
                            UserId = 8
                        },
                        new
                        {
                            AcctNo = 2135u,
                            AccountName = "Savings Account",
                            Balance = 35018,
                            UserId = 9
                        },
                        new
                        {
                            AcctNo = 6680u,
                            AccountName = "Savings Account",
                            Balance = 62609,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.Property<int>("Transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryString")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Sender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Transaction");

                    b.HasIndex("AccountId");

                    b.ToTable("UserHistories");

                    b.HasData(
                        new
                        {
                            Transaction = 1,
                            AccountId = 2135u,
                            Amount = -202.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2150),
                            HistoryString = "Account ID: 2135 --- Withdrawn: $202.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 2135u,
                            Type = "Withdraw"
                        },
                        new
                        {
                            Transaction = 2,
                            AccountId = 8839u,
                            Amount = 893.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2232),
                            HistoryString = "Account ID: 8839 --- Received: $893.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 2135u,
                            Type = "Receive"
                        },
                        new
                        {
                            Transaction = 3,
                            AccountId = 5181u,
                            Amount = -41.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2243),
                            HistoryString = "Account ID: 5181 --- Deposited: $41.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 5181u,
                            Type = "Deposit"
                        },
                        new
                        {
                            Transaction = 4,
                            AccountId = 2135u,
                            Amount = 166.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2250),
                            HistoryString = "Account ID: 2135 --- Received: $166.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 3937u,
                            Type = "Receive"
                        },
                        new
                        {
                            Transaction = 5,
                            AccountId = 5181u,
                            Amount = -494.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2256),
                            HistoryString = "Account ID: 5181 --- Sent: $494.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 7791u,
                            Type = "Send"
                        },
                        new
                        {
                            Transaction = 6,
                            AccountId = 5441u,
                            Amount = 836.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2263),
                            HistoryString = "Account ID: 5441 --- Received: $836.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 7524u,
                            Type = "Receive"
                        },
                        new
                        {
                            Transaction = 7,
                            AccountId = 5441u,
                            Amount = -88.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2268),
                            HistoryString = "Account ID: 5441 --- Sent: $88.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 6390u,
                            Type = "Send"
                        },
                        new
                        {
                            Transaction = 8,
                            AccountId = 6390u,
                            Amount = -767.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2274),
                            HistoryString = "Account ID: 6390 --- Deposited: $767.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 6390u,
                            Type = "Deposit"
                        },
                        new
                        {
                            Transaction = 9,
                            AccountId = 5291u,
                            Amount = -789.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2279),
                            HistoryString = "Account ID: 5291 --- Deposited: $789.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 5291u,
                            Type = "Deposit"
                        },
                        new
                        {
                            Transaction = 10,
                            AccountId = 6680u,
                            Amount = -36.0,
                            DateTime = new DateTime(2024, 10, 2, 22, 40, 8, 687, DateTimeKind.Local).AddTicks(2284),
                            HistoryString = "Account ID: 6680 --- Sent: $36.00 --- Date and Time: October 02, 2024 22:40 PM",
                            Sender = 6390u,
                            Type = "Send"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("AccountAcctNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountAcctNo");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "972 Samuel Phillips St.",
                            Age = 21u,
                            Email = "Christine.Robinson746@gmail.com",
                            FName = "Christine",
                            LName = "Robinson",
                            Password = "xSaxuJoHbv2i",
                            PhoneNumber = "+9616801591",
                            Username = "Christine.Robinson129"
                        },
                        new
                        {
                            Id = 2,
                            Address = "205 Jeffrey Martin St.",
                            Age = 39u,
                            Email = "Paul.Watson481@gmail.com",
                            FName = "Paul",
                            LName = "Watson",
                            Password = "VhA0jBMtEj30",
                            PhoneNumber = "+9612108257",
                            Username = "Paul.Watson677"
                        },
                        new
                        {
                            Id = 3,
                            Address = "83 Steven Lewis St.",
                            Age = 31u,
                            Email = "Brian.Edwards381@gmail.com",
                            FName = "Brian",
                            LName = "Edwards",
                            Password = "5dm706TEem6l",
                            PhoneNumber = "+9619954485",
                            Username = "Brian.Edwards208"
                        },
                        new
                        {
                            Id = 4,
                            Address = "703 Stephen Walker St.",
                            Age = 106u,
                            Email = "Raymond.Ward918@gmail.com",
                            FName = "Raymond",
                            LName = "Ward",
                            Password = "oXLWhyRQze0D",
                            PhoneNumber = "+9619016293",
                            Username = "Raymond.Ward613"
                        },
                        new
                        {
                            Id = 5,
                            Address = "7 William Lewis St.",
                            Age = 74u,
                            Email = "Rebecca.Thompson413@gmail.com",
                            FName = "Rebecca",
                            LName = "Thompson",
                            Password = "4idqNemvKokn",
                            PhoneNumber = "+9616432720",
                            Username = "Rebecca.Thompson266"
                        },
                        new
                        {
                            Id = 6,
                            Address = "220 Emma Campbell St.",
                            Age = 93u,
                            Email = "Matthew.Ward780@gmail.com",
                            FName = "Matthew",
                            LName = "Ward",
                            Password = "u3QPp8aoRqNX",
                            PhoneNumber = "+9615284552",
                            Username = "Matthew.Ward511"
                        },
                        new
                        {
                            Id = 7,
                            Address = "57 Paul Lee St.",
                            Age = 61u,
                            Email = "Gary.Ruiz653@gmail.com",
                            FName = "Gary",
                            LName = "Ruiz",
                            Password = "c8s9ys23O1eb",
                            PhoneNumber = "+9618706389",
                            Username = "Gary.Ruiz793"
                        },
                        new
                        {
                            Id = 8,
                            Address = "511 Kimberly Price St.",
                            Age = 91u,
                            Email = "Sharon.Nelson345@gmail.com",
                            FName = "Sharon",
                            LName = "Nelson",
                            Password = "ZbvJkh49jtIh",
                            PhoneNumber = "+9619698518",
                            Username = "Sharon.Nelson636"
                        },
                        new
                        {
                            Id = 9,
                            Address = "388 Amanda Wright St.",
                            Age = 58u,
                            Email = "Sandra.Evans781@gmail.com",
                            FName = "Sandra",
                            LName = "Evans",
                            Password = "2CzTbn7Bsy0i",
                            PhoneNumber = "+9617062497",
                            Username = "Sandra.Evans707"
                        },
                        new
                        {
                            Id = 10,
                            Address = "240 Mark Ramos St.",
                            Age = 69u,
                            Email = "Donald.Thompson989@gmail.com",
                            FName = "Donald",
                            LName = "Thompson",
                            Password = "TPIIbKdnt8cE",
                            PhoneNumber = "+9616922122",
                            Username = "Donald.Thompson333"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.HasOne("DataTierWebServer.Models.Account", null)
                        .WithMany("History")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserProfile", b =>
                {
                    b.HasOne("DataTierWebServer.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountAcctNo");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
